# .github/workflows/nextjs.yml

name: Next.js CI/CD Pipeline

# Trigger deployment on push to main and pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Set environment variables
env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g jest

      # Step 4: Lint check
      - name: Run Lint
        run: npm run lint

      # Step 6: Run tests
      - name: Run Unit Tests
        run: npm run test

      # Step 7: Build application
      - name: Build Next.js App
        run: npm run build

        # Deploy to Vercel
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: ./
