# .github/workflows/nextjs.yml

name: Next.js CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      # Build step (will create the out directory automatically)
      - name: Build Next.js App
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: "/${{ github.event.repository.name }}"

      # Configure for GitHub Pages
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          clean: true
