# .github/workflows/nextjs.yml

name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint || true # Make lint optional if not set up

      - name: Run Tests
        run: npm run test || true # Make tests optional if not set up

      - name: Build Next.js App
        run: npm run build
        env:
          NODE_ENV: production

      # Upload build output as artifact
      - name: Upload Build Output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: out

  # Deploy job
  deploy:
    needs: build # Wait for build job to complete
    runs-on: ubuntu-latest
    # Only run deploy on main branch pushes
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Download the build output
      - name: Download Build Output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: out

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
