# .github/workflows/nextjs.yml

name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: "/indproj"

      - name: Add .nojekyll file
        run: |
          touch ./out/.nojekyll
          cp -r .next/static ./out/_next/static || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
